### ISSUE TITLE
Ты не правильно понял меня. Смотри, есть несколько видов ассоциаций has_many:

### ISSUE THREAD

**Issue by The7Fame** [The7Fame/trainee-planner#19]
Ты не правильно понял меня. Смотри, есть несколько видов ассоциаций has_many:

1. [has_many](https://edgeguides.rubyonrails.org/association_basics.html#the-has-many-association)
2. [has_many :through](https://edgeguides.rubyonrails.org/association_basics.html#the-has-many-through-association)
3. [has_and_belongs_to_many](https://edgeguides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association)

Какая из этих ассоциаций тебе нужна? Можешь рассказать бизнес-логику, которую ты закладываешь, чтобы я тебя чуть что подправил

_Originally posted by @TsikhanauDzmitry in https://github.com/The7Fame/trainee-planner/pull/16#discussion_r1307443104_

**Comment by The7Fame** [comment]
Использую первый вариант. Чтобы в последующем получить все события пользователя: `@user.events`, а также все события, которые принадлежат категории: `@category.events`.

**Comment by TsikhanauDzmitry** [comment]
Можешь мне с точки зрения бизнес логики рассказать, как работают данные связи?

**Comment by The7Fame** [comment]
Есть пользователь, а у него события. Чтобы просмотреть все события пользователя , то `@user.events` - получаем список событий.

`has_many` - связь один-ко-многим показывает, что экземпляр модели имеет ноль или несколько экземпляров другого класса

`has_many :through` - связь многие-ко-многим, похожа на` has_many`, но есть прослойка, которая играют связующую роль между моделями.

`has_and_belongs_to` - cвязь многие-ко-многим, необходимо создать промежуточную таблицу. Например, есть модель Статья и модель Автор. У автора может быть много статей, а у статьи может быть много авторов.
